// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Shoe recommendation based on outfit image.
 *
 * - recommendShoes - A function that recommends shoes based on an outfit image.
 * - RecommendShoesInput - The input type for the recommendShoes function.
 * - RecommendShoesOutput - The return type for the recommendShoes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendShoesInputSchema = z.object({
  outfitImageDataUri: z
    .string()
    .describe(
      "A photo of an outfit, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type RecommendShoesInput = z.infer<typeof RecommendShoesInputSchema>;

const ShoeRecommendationSchema = z.object({
  shoeDescription: z.string().describe('Description of the recommended shoe.'),
  matchReason: z.string().describe('Why this shoe matches the outfit.'),
});

const RecommendShoesOutputSchema = z.array(ShoeRecommendationSchema).describe('Array of recommended shoes.');
export type RecommendShoesOutput = z.infer<typeof RecommendShoesOutputSchema>;

export async function recommendShoes(input: RecommendShoesInput): Promise<RecommendShoesOutput> {
  return recommendShoesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendShoesPrompt',
  input: {schema: RecommendShoesInputSchema},
  output: {schema: RecommendShoesOutputSchema},
  prompt: `You are a personal stylist recommending shoes based on an outfit.

  Analyze the style of the outfit in the image and recommend 3 pairs of shoes that would match the outfit.
  Explain why each shoe would be a good match.

  Outfit Image: {{media url=outfitImageDataUri}}
  `,
});

const recommendShoesFlow = ai.defineFlow(
  {
    name: 'recommendShoesFlow',
    inputSchema: RecommendShoesInputSchema,
    outputSchema: RecommendShoesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
